# Usage:
#
#     - uses: langston-barrett/mdlynx/.github/actions/mdlynx@SHA
#

name: mdlynx
description: Install and run mdlynx
inputs:
  version:
    description: version (without the leading 'v')
    required: false
    default: '0.3.0'
  target:
    description: Target triple
    required: false
    default: 'x86_64-unknown-linux-gnu'
runs:
  using: composite
  steps:
  - uses: langston-barrett/mdlynx/.github/actions/install-mdlynx@v0.3.0
    with:
      version: ${{ inputs.version }}
      target: ${{ inputs.target }}
  # Runners have 4 cores as of 2025-11
  # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
  - name: mdlynx
    shell: bash
    run: >
      git ls-files --exclude-standard '*.md' |
      xargs --max-args 1 --max-procs 4 mdlynx
