# Usage:
#
#     - uses: langston-barrett/mdlynx/.github/actions/install-mdlynx@SHA
#

name: Install mdlynx
description: Install mdlynx from GitHub Releases and add it to PATH
inputs:
  version:
    description: version (without the leading 'v')
    required: false
    default: '0.2.0'
  target:
    description: Target triple
    required: false
    default: 'x86_64-unknown-linux-gnu'
runs:
  using: composite
  steps:
    - name: Download and install mdlynx
      shell: bash
      # For why `env`, see https://docs.zizmor.sh/audits/#template-injection
      env:
        TARGET: ${{ inputs.target }}
        VERSION: ${{ inputs.version }}
      run: | # zizmor: ignore[github-env]
        set -euo pipefail
        install_dir="${HOME}/.local/bin"
        mkdir -p "${install_dir}"
        echo "${install_dir}" >> "${GITHUB_PATH}"
        file="mdlynx-${TARGET}"
        url="https://github.com/langston-barrett/mdlynx/releases/download/v${VERSION}/${file}"
        curl \
          --fail \
          --location \
          --proto '=https' \
          --show-error \
          --silent \
          --tlsv1.2 \
          --output "${install_dir}/mdlynx" \
          ${url}
        chmod +x "${install_dir}"/*
